import { Button } from "antd";
import type { NextPage } from "next";
import Head from "next/head";
import { web3Actions } from "../lib/web3";

const Home: NextPage = () => {
  return (
    <div className="bg-slate-800 h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full flex flex-col justify-center items-center">
        <h1 className="text-white text-4xl mb-4">ONGAMA NFT MARKET</h1>
        <Button className="text-white" onClick={web3Actions.connectWallet}>
          Connect Wallet
        </Button>
        <Button
          className="text-white mt-3"
          onClick={web3Actions.connectTrustWallet}
        >
          Connect with Trust Wallet
        </Button>
      </div>
    </div>
  );
};

export default Home;
